In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [2]:
!pip install "unsloth[kaggle-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install --no-deps xformers trl peft accelerate bitsandbytes
!pip install wandb

Collecting unsloth@ git+https://github.com/unslothai/unsloth.git (from unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git)
  Cloning https://github.com/unslothai/unsloth.git to /tmp/pip-install-g7mk9ug9/unsloth_ba8b05481b0d478dad68f7bfcfa8b9f1
  Running command git clone --filter=blob:none --quiet https://github.com/unslothai/unsloth.git /tmp/pip-install-g7mk9ug9/unsloth_ba8b05481b0d478dad68f7bfcfa8b9f1
  Resolved https://github.com/unslothai/unsloth.git to commit eb91752d4b80363d633d0bfee10dd2e24968f4f4
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: typer>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (0.24.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (13.9.4)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (2.12.3)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (6.0.3)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (1.6.0)
Requirement already satisfied: huggingface-hub>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (1.33.0)
Requirement already satisfied: structlog>=24.1.0 in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (26.1.0)
Requirement already satisfied: click>=8.0 in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (8.5.0)
Requirement already satisfied: bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5 in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (0.50.2)
Requirement already satisfied: torch<3,>=2.4 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (2.10.0+cu128)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (2.0.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (26.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.34.0->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.34.0->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.34.0->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.34.0->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (0.28.1)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.34.0->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (4.67.3)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.34.0->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (4.15.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.12.0->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.12.0->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (2.20.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (0.4.2)
Requirement already satisfied: unsloth_zoo>=2026.9.8 in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (2026.9.8)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (0.25.0+cu128)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.34.0->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.34.0->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.34.0->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.34.0->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.34.0->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (0.16.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (0.1.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (1.5.3)
Requirement already satisfied: torchao>=0.13.0 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.9.8->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (0.18.0)
Requirement already satisfied: tyro in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.9.8->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (1.0.16)
Requirement already satisfied: accelerate>=0.34.1 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.9.8->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (1.13.0)
Requirement already satisfied: trl!=0.19.0,<=1.13.0,>=0.18.2 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.9.8->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (0.24.0)
Requirement already satisfied: peft!=0.11.0,>=0.18.0 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.9.8->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (0.19.1)
Requirement already satisfied: cut_cross_entropy in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.9.8->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (25.1.1)
Requirement already satisfied: transformers!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.17.0,>=4.52.4 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.9.8->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (5.5.0)
Requirement already satisfied: datasets!=4.0.*,!=4.1.0,!=4.4.*,!=4.5.0,<5.0.0,>=3.4.1 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.9.8->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (4.3.0)
Requirement already satisfied: sentencepiece>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.9.8->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (0.2.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.9.8->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (5.9.5)
Requirement already satisfied: wheel>=0.42.0 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.9.8->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (0.47.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.9.8->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (5.29.5)
Requirement already satisfied: hf_transfer in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.9.8->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (0.1.9)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.9.8->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (11.3.0)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.9.8->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (2025.11.3)
Requirement already satisfied: msgspec in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.9.8->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (0.21.1)
Requirement already satisfied: diffusers>=0.39.0 in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (0.40.0)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[kaggle-new]@ git+https://github.com/unslothai/unsloth.git) (5.4.1)

In [3]:
from datasets import load_dataset

# Load dataset from Hugging Face
dataset = load_dataset("b-mc2/sql-create-context", split="train")

# Define the prompt template
prompt_template = """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
Write a SQL query to answer the following question: {question}

### Input (Database Schema):
{context}

### Response (SQL Query):
{answer}"""

# Formatting function
def format_prompts(batch):
    texts = []
    for question, context, answer in zip(batch["question"], batch["context"], batch["answer"]):
        text = prompt_template.format(question=question, context=context, answer=answer)
        # Append the EOS token so the model knows when to stop generating
        texts.append(text + tokenizer.eos_token)
    return {"text": texts}

# Map the formatting function to the dataset
dataset = dataset.map(format_prompts, batched=True)

README.md:   0%|          | 0.00/4.43k [00:00<?, ?B/s]

sql_create_context_v4.json: reconstructing file:   0%|          |  0.00B / 21.8MB

sql_create_context_v4.json: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/78577 [00:00<?, ? examples/s]

Map:   0%|          | 0/78577 [00:00<?, ? examples/s]

NameError: name 'tokenizer' is not defined

In [ ]:
from unsloth import FastLanguageModel
import torch

max_seq_length = 2048 # Good for text-to-SQL tasks

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/llama-3-8b-Instruct-bnb-4bit", # Pre-quantized for speed
    max_seq_length = max_seq_length,
    dtype = None, # Auto-detects float16 for T4
    load_in_4bit = True,
)

# Apply LoRA adapters
model = FastLanguageModel.get_peft_model(
    model,
    r = 16, # Rank
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 16,
    lora_dropout = 0, 
    bias = "none",
    use_gradient_checkpointing = "unsloth", 
)

In [ ]:
 from trl import SFTTrainer
from transformers import TrainingArguments
import wandb

# Initialize W&B run
wandb.init(project="Text-to-SQL-LLM", name="llama-3-8b-qlora")

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 10,
        max_steps = 200, # Start small to test, then increase for actual fine-tuning
        learning_rate = 2e-4,
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),
        logging_steps = 1,
        output_dir = "outputs",
        optim = "adamw_8bit",
        report_to = "wandb", # Logs to Weights & Biases
    ),
)

# Start training
trainer.train()

In [ ]:
# Enable native, 2x faster inference
FastLanguageModel.for_inference(model)

test_prompt = prompt_template.format(
    question="How many users signed up in 2026?",
    context="CREATE TABLE users (id INT, signup_date DATE, name VARCHAR);",
    answer=""
)

inputs = tokenizer([test_prompt], return_tensors = "pt").to("cuda")

outputs = model.generate(**inputs, max_new_tokens = 64, use_cache = True)
print(tokenizer.batch_decode(outputs, skip_special_tokens = True)[0])

In [ ]:
# 1. Install Unsloth and required libraries
!pip install "unsloth[kaggle-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install --no-deps xformers trl peft accelerate bitsandbytes
!pip install wandb

# 2. Login to Hugging Face and W&B using Kaggle Secrets
from kaggle_secrets import UserSecretsClient
import wandb
from huggingface_hub import login

user_secrets = UserSecretsClient()
hf_token = user_secrets.get_secret("HF_TOKEN")
wandb_key = user_secrets.get_secret("WANDB_API_KEY")

login(token=hf_token)
wandb.login(key=wandb_key)

In [ ]:
from datasets import load_dataset

# Load the SQL dataset
dataset = load_dataset("b-mc2/sql-create-context", split="train")

# Define how the LLM should see the data
prompt_template = """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
Write a SQL query to answer the following question: {question}

### Input (Database Schema):
{context}

### Response (SQL Query):
{answer}"""

# Apply the formatting to the entire dataset
def format_prompts(batch):
    texts = []
    for question, context, answer in zip(batch["question"], batch["context"], batch["answer"]):
        text = prompt_template.format(question=question, context=context, answer=answer)
        texts.append(text) 
    return {"text": texts}

dataset = dataset.map(format_prompts, batched=True)

# Print one example to verify it looks correct
print(dataset[0]["text"])

In [ ]:
from trl import SFTTrainer
from transformers import TrainingArguments
import wandb

# Initialize Weights & Biases
wandb.init(project="Text-to-SQL-LLM", name="llama-3-8b-qlora-run1")

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 10,
        max_steps = 60, # Small number of steps for testing
        learning_rate = 2e-4,
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),
        logging_steps = 1,
        output_dir = "outputs",
        optim = "adamw_8bit",
        report_to = "wandb", # Sends training graphs to W&B
    ),
)

# Execute Fine-Tuning
trainer.train()
wandb.finish()

In [ ]:
from unsloth import FastLanguageModel
import torch
from datasets import load_dataset

# 1. Load the Model & Tokenizer FIRST
max_seq_length = 2048
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/llama-3-8b-Instruct-bnb-4bit",
    max_seq_length = max_seq_length,
    dtype = None,
    load_in_4bit = True,
)

# 2. Add LoRA Adapters (This makes fine-tuning possible on a T4 GPU)
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 16,
    lora_dropout = 0, 
    bias = "none",
    use_gradient_checkpointing = "unsloth", 
)

# 3. Load and Format Dataset NOW (since the tokenizer is ready)
dataset = load_dataset("b-mc2/sql-create-context", split="train")

prompt_template = """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
Write a SQL query to answer the following question: {question}

### Input (Database Schema):
{context}

### Response (SQL Query):
{answer}"""

def format_prompts(batch):
    texts = []
    for question, context, answer in zip(batch["question"], batch["context"], batch["answer"]):
        text = prompt_template.format(question=question, context=context, answer=answer)
        # Append the EOS token so the model knows when to stop generating text
        texts.append(text + tokenizer.eos_token)
    return {"text": texts}

dataset = dataset.map(format_prompts, batched=True)
print("\n✅ Dataset formatted! First example:")
print(dataset[0]["text"])

In [ ]:
# 1. Login to Hugging Face and W&B
from kaggle_secrets import UserSecretsClient
import wandb
from huggingface_hub import login

try:
    user_secrets = UserSecretsClient()
    hf_token = user_secrets.get_secret("HF_TOKEN")
    wandb_key = user_secrets.get_secret("WANDB_API_KEY")
    
    print("✅ Secrets loaded successfully!")
    
    # Log in using the loaded keys
    login(token=hf_token)
    wandb.login(key=wandb_key)
    print("✅ Successfully logged into Hugging Face and W&B!")
    
except Exception as e:
    print("❌ ERROR: Could not find secrets. Make sure the checkboxes in Add-ons -> Secrets are ticked!")
    print(e)

In [ ]:
from unsloth import FastLanguageModel
import torch
from datasets import load_dataset

# 1. Load the Model & Tokenizer
max_seq_length = 2048
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/llama-3-8b-Instruct-bnb-4bit",
    max_seq_length = max_seq_length,
    dtype = None,
    load_in_4bit = True,
)

# 2. Add LoRA Adapters (This makes fine-tuning possible on a single T4 GPU)
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 16,
    lora_dropout = 0, 
    bias = "none",
    use_gradient_checkpointing = "unsloth", 
)

# 3. Load and Format Dataset 
dataset = load_dataset("b-mc2/sql-create-context", split="train")

prompt_template = """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
Write a SQL query to answer the following question: {question}

### Input (Database Schema):
{context}

### Response (SQL Query):
{answer}"""

def format_prompts(batch):
    texts = []
    for question, context, answer in zip(batch["question"], batch["context"], batch["answer"]):
        text = prompt_template.format(question=question, context=context, answer=answer)
        # Append the EOS token so the model knows when to stop generating text
        texts.append(text + tokenizer.eos_token)
    return {"text": texts}

dataset = dataset.map(format_prompts, batched=True)
print("\n✅ Dataset formatted! First example:")
print(dataset[0]["text"])

In [ ]:
# 1. Login to Hugging Face and W&B
from kaggle_secrets import UserSecretsClient
import wandb
from huggingface_hub import login

user_secrets = UserSecretsClient()
hf_token = user_secrets.get_secret("HF_TOKEN")
wandb_key = user_secrets.get_secret("WANDB_API_KEY")

login(token=hf_token)
wandb.login(key=wandb_key)
print("✅ Successfully logged into Hugging Face and W&B!")

In [ ]:
import unsloth
from unsloth import FastLanguageModel
import torch
from datasets import load_dataset

# 1. Load the Model & Tokenizer
max_seq_length = 2048
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/llama-3-8b-Instruct-bnb-4bit",
    max_seq_length = max_seq_length,
    dtype = None,
    load_in_4bit = True,
)

# 2. Add LoRA Adapters
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 16,
    lora_dropout = 0, 
    bias = "none",
    use_gradient_checkpointing = "unsloth", 
)

# 3. Load and Format Dataset 
dataset = load_dataset("b-mc2/sql-create-context", split="train")

prompt_template = """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
Write a SQL query to answer the following question: {question}

### Input (Database Schema):
{context}

### Response (SQL Query):
{answer}"""

def format_prompts(batch):
    texts = []
    for question, context, answer in zip(batch["question"], batch["context"], batch["answer"]):
        text = prompt_template.format(question=question, context=context, answer=answer)
        texts.append(text + tokenizer.eos_token)
    return {"text": texts}

dataset = dataset.map(format_prompts, batched=True)
print("\n✅ Dataset formatted! First example:")
print(dataset[0]["text"])

In [ ]:
!pip install "unsloth[kaggle-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install --no-deps xformers trl peft accelerate bitsandbytes
!pip install wandb

In [4]:
!pip install --upgrade huggingface_hub transformers

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (1.33.0)
Collecting huggingface_hub
  Downloading huggingface_hub-2.0.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.5.0)
Collecting transformers
  Using cached transformers-5.17.0-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.6.0)
Collecting httpx2<3,>=2.0.0 (from huggingface_hub)
  Downloading httpx2-2.13.1-py3-none-any.whl.metadata (9.8 kB)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (6.0.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.67.3)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Collecting tokenizers<0.24.0,>=0.23.1 (from transformers)
  Downloading tokenizers-0.23.2-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.8 kB)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.2)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.8.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.28.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Collecting httpcore2==2.13.1 (from httpx2<3,>=2.0.0->huggingface_hub)
  Downloading httpcore2-2.13.1-py3-none-any.whl.metadata (26 kB)
Collecting idna (from httpx<1,>=0.23.0->huggingface_hub)
  Downloading idna-3.20-py3-none-any.whl.metadata (7.2 kB)
Collecting truststore>=0.10 (from httpx2<3,>=2.0.0->huggingface_hub)
  Downloading truststore-0.10.4-py3-none-any.whl.metadata (4.4 kB)
Downloading transformers-5.17.0-py3-none-any.whl (12.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 52.5 MB/s eta 0:00:0000:0100:01
Downloading tokenizers-0.23.2-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 91.0 MB/s eta 0:00:00:00:01
Downloading idna-3.20-py3-none-any.whl (69 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.6/69.6 kB 4.2 MB/s eta 0:00:00
Installing collected packages: idna, tokenizers, transformers
  Attempting uninstall: idna
    Found existing installation: idna 3.13
    Uninstalling idna-3.13:
      Successfully uninstalled idna-3.13
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.22.2
    Uninstalling tokenizers-0.22.2:
      Successfully uninstalled tokenizers-0.22.2
  Attempting uninstall: transformers
    Found existing installation: transformers 5.5.0
    Uninstalling transformers-5.5.0:
      Successfully uninstalled transformers-5.5.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-adk 1.29.0 requires google-cloud-bigquery-storage>=2.0.0, which is not installed.
Successfully installed idna-3.20 tokenizers-0.23.2 transformers-5.17.0

In [5]:
import unsloth
from unsloth import FastLanguageModel
import torch
from datasets import load_dataset

print("⏳ 1. Loading Model and Tokenizer (This takes 1-2 minutes)...")
max_seq_length = 2048
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/llama-3-8b-Instruct-bnb-4bit",
    max_seq_length = max_seq_length,
    dtype = None,
    load_in_4bit = True,
)

print("⏳ 2. Applying LoRA adapters...")
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 16,
    lora_dropout = 0, 
    bias = "none",
    use_gradient_checkpointing = "unsloth", 
)

print("⏳ 3. Downloading and formatting dataset...")
dataset = load_dataset("b-mc2/sql-create-context", split="train")

prompt_template = """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
Write a SQL query to answer the following question: {question}

### Input (Database Schema):
{context}

### Response (SQL Query):
{answer}"""

def format_prompts(batch):
    texts = []
    for question, context, answer in zip(batch["question"], batch["context"], batch["answer"]):
        text = prompt_template.format(question=question, context=context, answer=answer)
        # Append the EOS token so the model knows when to stop generating
        texts.append(text + tokenizer.eos_token)
    return {"text": texts}

dataset = dataset.map(format_prompts, batched=True)
print("\n✅ SUCCESS! Dataset formatted! First example:")
print(dataset[0]["text"])

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
⏳ 1. Loading Model and Tokenizer (This takes 1-2 minutes)...
==((====))==  Unsloth 2026.9.12: Fast Llama patching. Transformers: 5.17.0.
   \\   /|    Tesla T4. Num GPUs = 2. Max memory: 14.562 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

/usr/local/lib/python3.12/dist-packages/huggingface_hub/constants.py:302: FutureWarning: The `HF_HUB_ENABLE_HF_TRANSFER` environment variable is deprecated as 'hf_transfer' is not used anymore. Please use `HF_XET_HIGH_PERFORMANCE` instead to enable high performance transfer with Xet. Visit https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables#hfxethighperformance for more details.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/constants.py:302: FutureWarning: The `HF_HUB_ENABLE_HF_TRANSFER` environment variable is deprecated as 'hf_transfer' is not used anymore. Please use `HF_XET_HIGH_PERFORMANCE` instead to enable high performance transfer with Xet. Visit https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables#hfxethighperformance for more details.
  warnings.warn(

total weights      : 5.208 GiB
no_split classes   : ['LlamaDecoderLayer']
output head        : lm_head -> cuda:1
head headroom      : 0.342 GiB
activation reserve : 10.191 GiB requested
  cuda:0  budget  12.95 GiB  weights  2.705 GiB  free 10.247 GiB  reserve 10.191 GiB
  cuda:1  budget  12.98 GiB  weights  2.502 GiB  free 10.476 GiB  reserve 10.033 GiB   <- output head
note: Bnb4BitHfQuantizer.adjust_max_memory lowered the budget on cuda:0 14.391 -> 12.952 GiB, cuda:1 14.421 -> 12.979 GiB (memory the quantiser keeps for its own load-time buffers)

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

Unsloth: Will load unsloth/llama-3-8b-Instruct-bnb-4bit as a legacy tokenizer.

⏳ 2. Applying LoRA adapters...

Unsloth 2026.9.12 patched 32 layers with 32 QKV layers, 32 O layers and 32 MLP layers.

⏳ 3. Downloading and formatting dataset...

Map:   0%|          | 0/78577 [00:00<?, ? examples/s]

✅ SUCCESS! Dataset formatted! First example:
Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
Write a SQL query to answer the following question: How many heads of the departments are older than 56 ?

### Input (Database Schema):
CREATE TABLE head (age INTEGER)

### Response (SQL Query):
SELECT COUNT(*) FROM head WHERE age > 56<|eot_id|>

In [8]:
from trl import SFTTrainer
from transformers import TrainingArguments
import wandb

# Initialize Weights & Biases
wandb.init(project="Text-to-SQL-LLM", name="llama-3-8b-qlora-run1")

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 10,
        max_steps = 60, # 60 steps for a quick test run
        learning_rate = 2e-4,
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),
        logging_steps = 1,
        output_dir = "outputs",
        optim = "adamw_8bit",
        report_to = "wandb", 
    ),
)

# Execute Fine-Tuning
trainer.train()
wandb.finish()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 2
   \\   /|    Num examples = 78,577 | Num Epochs = 1 | Total steps = 60
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 41,943,040 of 8,072,204,288 (0.52% trained)

In [9]:
# 1. Put the model into high-speed inference mode
FastLanguageModel.for_inference(model)

# 2. Give it a brand new question and database schema
test_prompt = prompt_template.format(
    question="What is the total revenue for the electronics department in 2026?",
    context="CREATE TABLE sales (department VARCHAR, revenue DECIMAL, sale_year INTEGER)",
    answer="" # Leave this blank, the AI will fill it in!
)

# 3. Translate the text into numbers for the AI
inputs = tokenizer([test_prompt], return_tensors = "pt").to("cuda")

# 4. Generate the SQL!
outputs = model.generate(**inputs, max_new_tokens = 64, use_cache = True)

# 5. Print the result
print("\n🤖 AI GENERATED SQL:")
print(tokenizer.batch_decode(outputs, skip_special_tokens = True)[0])

Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Ignoring clean_up_tokenization_spaces=True for BPE tokenizer TokenizersBackend. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

🤖 AI GENERATED SQL:
Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
Write a SQL query to answer the following question: What is the total revenue for the electronics department in 2026?

### Input (Database Schema):
CREATE TABLE sales (department VARCHAR, revenue DECIMAL, sale_year INTEGER)

### Response (SQL Query):
SELECT SUM(revenue) FROM sales WHERE department = "Electronics" AND sale_year = 2026

In [10]:
import pandas as pd
from tqdm import tqdm

# 1. Grab 100 examples from the end of the dataset (unseen data)
test_data = dataset.select(range(len(dataset)-100, len(dataset)))
FastLanguageModel.for_inference(model)

correct_matches = 0
total_tested = len(test_data)
results = []

print(f"Starting evaluation on {total_tested} test queries...\n")

for i in tqdm(range(total_tested)):
    question = test_data[i]["question"]
    context = test_data[i]["context"]
    true_sql = test_data[i]["answer"]
    
    # Format the prompt WITHOUT the answer
    test_prompt = prompt_template.format(
        question=question, 
        context=context, 
        answer=""
    )
    
    # Generate the prediction
    inputs = tokenizer([test_prompt], return_tensors="pt").to("cuda")
    prompt_length = inputs.input_ids.shape[1]
    
    outputs = model.generate(**inputs, max_new_tokens=64, use_cache=True, pad_token_id=tokenizer.eos_token_id)
    
    # Extract only the newly generated text (ignoring the prompt)
    generated_tokens = outputs[0][prompt_length:]
    generated_sql = tokenizer.decode(generated_tokens, skip_special_tokens=True).strip()
    
    # Normalize strings (lowercase and remove extra spaces) for fair comparison
    pred_normalized = " ".join(generated_sql.lower().split())
    true_normalized = " ".join(true_sql.lower().split())
    
    # Check if Exact Match
    is_correct = (pred_normalized == true_normalized)
    if is_correct:
        correct_matches += 1
        
    results.append({
        "Question": question,
        "True SQL": true_sql,
        "Generated SQL": generated_sql,
        "Exact Match": is_correct
    })

# Calculate Final Metrics
accuracy = (correct_matches / total_tested) * 100
print(f"\n✅ Evaluation Complete!")
print(f"📊 Exact Match (EM) Accuracy: {accuracy:.2f}%")

# Save the results to a CSV so you can put it on your GitHub
df_results = pd.DataFrame(results)
df_results.to_csv("text_to_sql_evaluation_results.csv", index=False)
print("💾 Saved detailed results to 'text_to_sql_evaluation_results.csv'")

Starting evaluation on 100 test queries...

  0%|          | 0/100 [00:00<?, ?it/s]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  1%|          | 1/100 [00:02<04:09,  2.52s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  2%|▏         | 2/100 [00:04<03:25,  2.09s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  3%|▎         | 3/100 [00:05<02:48,  1.74s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  4%|▍         | 4/100 [00:06<02:25,  1.51s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  5%|▌         | 5/100 [00:08<02:23,  1.51s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  6%|▌         | 6/100 [00:10<02:46,  1.77s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  7%|▋         | 7/100 [00:12<02:44,  1.77s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  8%|▊         | 8/100 [00:13<02:31,  1.65s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  9%|▉         | 9/100 [00:15<02:23,  1.58s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 10%|█         | 10/100 [00:16<02:26,  1.62s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 11%|█         | 11/100 [00:18<02:19,  1.57s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 12%|█▏        | 12/100 [00:19<02:20,  1.59s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 13%|█▎        | 13/100 [00:22<02:34,  1.77s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 14%|█▍        | 14/100 [00:24<02:40,  1.86s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 15%|█▌        | 15/100 [00:26<02:36,  1.84s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 16%|█▌        | 16/100 [00:27<02:35,  1.85s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 17%|█▋        | 17/100 [00:29<02:39,  1.92s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 18%|█▊        | 18/100 [00:32<02:44,  2.01s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 19%|█▉        | 19/100 [00:34<02:50,  2.10s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 20%|██        | 20/100 [00:36<02:37,  1.97s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 21%|██        | 21/100 [00:38<02:34,  1.96s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 22%|██▏       | 22/100 [00:39<02:16,  1.75s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 23%|██▎       | 23/100 [00:42<02:38,  2.06s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 24%|██▍       | 24/100 [00:43<02:16,  1.80s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 25%|██▌       | 25/100 [00:45<02:28,  1.98s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 26%|██▌       | 26/100 [00:47<02:15,  1.83s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 27%|██▋       | 27/100 [00:48<02:07,  1.75s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 28%|██▊       | 28/100 [00:50<01:55,  1.60s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 29%|██▉       | 29/100 [00:51<01:57,  1.65s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 30%|███       | 30/100 [00:53<01:54,  1.63s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 31%|███       | 31/100 [00:55<02:01,  1.76s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 32%|███▏      | 32/100 [00:57<02:00,  1.78s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 33%|███▎      | 33/100 [00:58<01:52,  1.68s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 34%|███▍      | 34/100 [01:00<01:49,  1.65s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 35%|███▌      | 35/100 [01:02<01:51,  1.71s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 36%|███▌      | 36/100 [01:03<01:43,  1.61s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 37%|███▋      | 37/100 [01:04<01:35,  1.52s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 38%|███▊      | 38/100 [01:06<01:40,  1.62s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 39%|███▉      | 39/100 [01:08<01:47,  1.76s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 40%|████      | 40/100 [01:11<01:55,  1.92s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 41%|████      | 41/100 [01:12<01:43,  1.75s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 42%|████▏     | 42/100 [01:14<01:39,  1.72s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 43%|████▎     | 43/100 [01:15<01:30,  1.59s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 44%|████▍     | 44/100 [01:16<01:25,  1.53s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 45%|████▌     | 45/100 [01:17<01:19,  1.44s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 46%|████▌     | 46/100 [01:19<01:18,  1.45s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 47%|████▋     | 47/100 [01:21<01:31,  1.73s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 48%|████▊     | 48/100 [01:22<01:20,  1.54s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 49%|████▉     | 49/100 [01:24<01:15,  1.49s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 50%|█████     | 50/100 [01:25<01:08,  1.37s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 51%|█████     | 51/100 [01:27<01:14,  1.51s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 52%|█████▏    | 52/100 [01:29<01:17,  1.61s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 53%|█████▎    | 53/100 [01:30<01:09,  1.47s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 54%|█████▍    | 54/100 [01:31<01:05,  1.43s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 55%|█████▌    | 55/100 [01:32<01:02,  1.39s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 56%|█████▌    | 56/100 [01:34<01:00,  1.36s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 57%|█████▋    | 57/100 [01:35<00:56,  1.33s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 58%|█████▊    | 58/100 [01:36<00:54,  1.30s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 59%|█████▉    | 59/100 [01:38<00:57,  1.40s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 60%|██████    | 60/100 [01:40<01:03,  1.58s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 61%|██████    | 61/100 [01:42<01:04,  1.65s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 62%|██████▏   | 62/100 [01:43<01:00,  1.58s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 63%|██████▎   | 63/100 [01:44<00:55,  1.50s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 64%|██████▍   | 64/100 [01:46<00:54,  1.50s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 65%|██████▌   | 65/100 [01:47<00:50,  1.44s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 66%|██████▌   | 66/100 [01:48<00:47,  1.41s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

✅ Evaluation Complete!
📊 Exact Match (EM) Accuracy: 71.00%
💾 Saved detailed results to 'text_to_sql_evaluation_results.csv'

In [11]:
# 2. Add LoRA Adapters (UPDATED for higher accuracy)
model = FastLanguageModel.get_peft_model(
    model,
    r = 32,            # INCREASED from 16
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 32,   # INCREASED from 16
    lora_dropout = 0, 
    bias = "none",
    use_gradient_checkpointing = "unsloth", 
)

TypeError: Unsloth: Your model already has LoRA adapters. Your new parameters are different.

In [ ]:
from trl import SFTTrainer
from transformers import TrainingArguments
import wandb

# Initialize Weights & Biases for Run 2
wandb.init(project="Text-to-SQL-LLM", name="llama-3-8b-qlora-1epoch")

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = 2048,
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 100,             # Increased to give the model time to warm up
        num_train_epochs = 1,           # ONE FULL EPOCH (replaces max_steps)
        learning_rate = 2e-4,
        lr_scheduler_type = "cosine",   # ADDED: Smooths out the learning curve
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),
        logging_steps = 10,
        output_dir = "outputs",
        optim = "adamw_8bit",
        report_to = "wandb", 
    ),
)

# Execute Fine-Tuning
trainer.train()
wandb.finish()

In [12]:
# 1. Reload the base model fresh
max_seq_length = 2048
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/llama-3-8b-Instruct-bnb-4bit",
    max_seq_length = max_seq_length,
    dtype = None,
    load_in_4bit = True,
)

# 2. Apply the new, upgraded LoRA adapters (r = 32)
model = FastLanguageModel.get_peft_model(
    model,
    r = 32,            # Upgraded for higher capacity
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 32,   # Upgraded to match r
    lora_dropout = 0, 
    bias = "none",
    use_gradient_checkpointing = "unsloth", 
)

print("✅ Model successfully reset and upgraded with r=32 adapters!")

==((====))==  Unsloth 2026.9.12: Fast Llama patching. Transformers: 5.17.0.
   \\   /|    Tesla T4. Num GPUs = 2. Max memory: 14.562 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

/usr/local/lib/python3.12/dist-packages/huggingface_hub/constants.py:302: FutureWarning: The `HF_HUB_ENABLE_HF_TRANSFER` environment variable is deprecated as 'hf_transfer' is not used anymore. Please use `HF_XET_HIGH_PERFORMANCE` instead to enable high performance transfer with Xet. Visit https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables#hfxethighperformance for more details.
  warnings.warn(

total weights      : 5.208 GiB
no_split classes   : ['LlamaDecoderLayer']
output head        : lm_head -> cuda:1
head headroom      : 0.342 GiB
activation reserve : 7.334 GiB requested
  cuda:0  budget  10.00 GiB  weights  2.604 GiB  free  7.394 GiB  reserve  7.334 GiB
  cuda:1  budget  10.22 GiB  weights  2.604 GiB  free  7.617 GiB  reserve  7.275 GiB   <- output head
note: Bnb4BitHfQuantizer.adjust_max_memory lowered the budget on cuda:0 11.108 -> 9.997 GiB, cuda:1 11.356 -> 10.221 GiB (memory the quantiser keeps for its own load-time buffers)

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

Unsloth: Will load unsloth/llama-3-8b-Instruct-bnb-4bit as a legacy tokenizer.

✅ Model successfully reset and upgraded with r=32 adapters!

In [13]:
from unsloth import FastLanguageModel
import torch

# 1. Reload the base model fresh
max_seq_length = 2048
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/llama-3-8b-Instruct-bnb-4bit",
    max_seq_length = max_seq_length,
    dtype = None,
    load_in_4bit = True,
)

# 2. Apply the upgraded LoRA adapters (r = 32)
model = FastLanguageModel.get_peft_model(
    model,
    r = 32,            # Upgraded for higher capacity
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 32,   # Upgraded to match r
    lora_dropout = 0, 
    bias = "none",
    use_gradient_checkpointing = "unsloth", 
)

print("✅ Model successfully reset and upgraded with r=32 adapters!")

==((====))==  Unsloth 2026.9.12: Fast Llama patching. Transformers: 5.17.0.
   \\   /|    Tesla T4. Num GPUs = 2. Max memory: 14.562 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

/usr/local/lib/python3.12/dist-packages/huggingface_hub/constants.py:302: FutureWarning: The `HF_HUB_ENABLE_HF_TRANSFER` environment variable is deprecated as 'hf_transfer' is not used anymore. Please use `HF_XET_HIGH_PERFORMANCE` instead to enable high performance transfer with Xet. Visit https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables#hfxethighperformance for more details.
  warnings.warn(

total weights      : 5.208 GiB
no_split classes   : ['LlamaDecoderLayer']
output head        : lm_head -> cuda:1
head headroom      : 0.342 GiB
activation reserve : 4.931 GiB requested
  cuda:0  budget   7.60 GiB  weights  2.604 GiB  free  4.992 GiB  reserve  4.931 GiB
  cuda:1  budget   7.82 GiB  weights  2.604 GiB  free  5.212 GiB  reserve  4.870 GiB   <- output head
note: Bnb4BitHfQuantizer.adjust_max_memory lowered the budget on cuda:0 8.440 -> 7.596 GiB, cuda:1 8.684 -> 7.816 GiB (memory the quantiser keeps for its own load-time buffers)

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

Unsloth: Will load unsloth/llama-3-8b-Instruct-bnb-4bit as a legacy tokenizer.

✅ Model successfully reset and upgraded with r=32 adapters!

In [14]:
from trl import SFTTrainer
from transformers import TrainingArguments
import wandb

# Initialize Weights & Biases for the full training run
wandb.init(project="Text-to-SQL-LLM", name="llama-3-8b-qlora-1epoch")

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = 2048,
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 100,             
        num_train_epochs = 1,           # Trains on the entire dataset once
        learning_rate = 2e-4,
        lr_scheduler_type = "cosine",   # Smooths out the learning curve
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),
        logging_steps = 10,
        output_dir = "outputs",
        optim = "adamw_8bit",
        report_to = "wandb", 
    ),
)

# Execute Full Fine-Tuning
trainer.train()
wandb.finish()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 2
   \\   /|    Num examples = 78,577 | Num Epochs = 1 | Total steps = 9,823
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 83,886,080 of 8,114,147,328 (1.03% trained)

Unsloth: Double buffering enabled (parallel H2D + compute) for backward pass.
Unsloth: Will smartly offload gradients to save VRAM!

KeyboardInterrupt:

In [ ]:
import pandas as pd
from tqdm import tqdm

# 1. Grab 100 test examples from the dataset that the model hasn't seen
test_data = dataset.select(range(len(dataset)-100, len(dataset)))
FastLanguageModel.for_inference(model)

correct_matches = 0
total_tested = len(test_data)
results = []

print(f"Starting evaluation on {total_tested} test queries...\n")

for i in tqdm(range(total_tested)):
    question = test_data[i]["question"]
    context = test_data[i]["context"]
    true_sql = test_data[i]["answer"]
    
    # Format prompt without the answer
    test_prompt = prompt_template.format(
        question=question, 
        context=context, 
        answer=""
    )
    
    inputs = tokenizer([test_prompt], return_tensors="pt").to("cuda")
    prompt_length = inputs.input_ids.shape[1]
    
    # Generate SQL prediction
    outputs = model.generate(**inputs, max_new_tokens=64, use_cache=True, pad_token_id=tokenizer.eos_token_id)
    
    generated_tokens = outputs[0][prompt_length:]
    generated_sql = tokenizer.decode(generated_tokens, skip_special_tokens=True).strip()
    
    # Normalize strings for fair comparison
    pred_normalized = " ".join(generated_sql.lower().split())
    true_normalized = " ".join(true_sql.lower().split())
    
    is_correct = (pred_normalized == true_normalized)
    if is_correct:
        correct_matches += 1
        
    results.append({
        "Question": question,
        "True SQL": true_sql,
        "Generated SQL": generated_sql,
        "Exact Match": is_correct
    })

# Compute final percentage
accuracy = (correct_matches / total_tested) * 100
print(f"\n✅ Evaluation Complete!")
print(f"📊 Exact Match (EM) Accuracy: {accuracy:.2f}%")

In [16]:
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = 2048,
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 50,             
        max_steps = 1000,               # CHANGED: 1,000 steps is plenty for a killer portfolio project
        learning_rate = 2e-4,
        lr_scheduler_type = "cosine",   
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),
        logging_steps = 10,
        output_dir = "outputs",
        optim = "adamw_8bit",
        report_to = "wandb", 
    ),
)

In [17]:
from unsloth import FastLanguageModel
import torch
from trl import SFTTrainer
from transformers import TrainingArguments
import wandb

print("⏳ 1. Resetting model with r=32 adapters...")
max_seq_length = 2048
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/llama-3-8b-Instruct-bnb-4bit",
    max_seq_length = max_seq_length,
    dtype = None,
    load_in_4bit = True,
)

model = FastLanguageModel.get_peft_model(
    model,
    r = 32,            
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 32,   
    lora_dropout = 0, 
    bias = "none",
    use_gradient_checkpointing = "unsloth", 
)

print("🚀 2. Starting optimized 1,000-step training run...")
wandb.init(project="Text-to-SQL-LLM", name="llama-3-8b-qlora-1000steps")

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset, # Uses the dataset we formatted earlier
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 50,             
        max_steps = 1000,               # Optimized sweet spot (~1.5 hours)
        learning_rate = 2e-4,
        lr_scheduler_type = "cosine",   
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),
        logging_steps = 10,
        output_dir = "outputs",
        optim = "adamw_8bit",
        report_to = "wandb", 
    ),
)

trainer.train()
wandb.finish()
print("✅ Training complete!")

⏳ 1. Resetting model with r=32 adapters...
==((====))==  Unsloth 2026.9.12: Fast Llama patching. Transformers: 5.17.0.
   \\   /|    Tesla T4. Num GPUs = 2. Max memory: 14.562 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

/usr/local/lib/python3.12/dist-packages/huggingface_hub/constants.py:302: FutureWarning: The `HF_HUB_ENABLE_HF_TRANSFER` environment variable is deprecated as 'hf_transfer' is not used anymore. Please use `HF_XET_HIGH_PERFORMANCE` instead to enable high performance transfer with Xet. Visit https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables#hfxethighperformance for more details.
  warnings.warn(

total weights      : 5.208 GiB
no_split classes   : ['LlamaDecoderLayer']
output head        : lm_head -> cuda:1
head headroom      : 0.342 GiB
activation reserve : 4.496 GiB requested
  cuda:0  budget   7.19 GiB  weights  2.604 GiB  free  4.585 GiB  reserve  4.496 GiB
  cuda:1  budget   7.35 GiB  weights  2.604 GiB  free  4.748 GiB  reserve  4.406 GiB   <- output head
note: Bnb4BitHfQuantizer.adjust_max_memory lowered the budget on cuda:0 7.987 -> 7.188 GiB, cuda:1 8.169 -> 7.352 GiB (memory the quantiser keeps for its own load-time buffers)

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

Unsloth: Will load unsloth/llama-3-8b-Instruct-bnb-4bit as a legacy tokenizer.

🚀 2. Starting optimized 1,000-step training run...

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 2
   \\   /|    Num examples = 78,577 | Num Epochs = 1 | Total steps = 1,000
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 83,886,080 of 8,114,147,328 (1.03% trained)

Unsloth: Restored added_tokens_decoder metadata in outputs/checkpoint-500/tokenizer_config.json.
Unsloth: Restored added_tokens_decoder metadata in outputs/checkpoint-1000/tokenizer_config.json.

✅ Training complete!

In [18]:
import pandas as pd
from tqdm import tqdm
from unsloth import FastLanguageModel

# 1. Grab 100 test examples from the end of the dataset (unseen data)
test_data = dataset.select(range(len(dataset)-100, len(dataset)))
FastLanguageModel.for_inference(model)

correct_matches = 0
total_tested = len(test_data)
results = []

print(f"Starting evaluation on {total_tested} test queries...\n")

for i in tqdm(range(total_tested)):
    question = test_data[i]["question"]
    context = test_data[i]["context"]
    true_sql = test_data[i]["answer"]
    
    # Format the prompt WITHOUT the answer
    test_prompt = prompt_template.format(
        question=question, 
        context=context, 
        answer=""
    )
    
    # Generate the prediction
    inputs = tokenizer([test_prompt], return_tensors="pt").to("cuda")
    prompt_length = inputs.input_ids.shape[1]
    
    outputs = model.generate(**inputs, max_new_tokens=64, use_cache=True, pad_token_id=tokenizer.eos_token_id)
    
    generated_tokens = outputs[0][prompt_length:]
    generated_sql = tokenizer.decode(generated_tokens, skip_special_tokens=True).strip()
    
    # Normalize strings for fair comparison
    pred_normalized = " ".join(generated_sql.lower().split())
    true_normalized = " ".join(true_sql.lower().split())
    
    is_correct = (pred_normalized == true_normalized)
    if is_correct:
        correct_matches += 1
        
    results.append({
        "Question": question,
        "True SQL": true_sql,
        "Generated SQL": generated_sql,
        "Exact Match": is_correct
    })

accuracy = (correct_matches / total_tested) * 100
print(f"\n✅ Evaluation Complete!")
print(f"📊 New Exact Match (EM) Accuracy: {accuracy:.2f}%")

# Save the results to a CSV
df_results = pd.DataFrame(results)
df_results.to_csv("text_to_sql_evaluation_results.csv", index=False)
print("💾 Saved detailed results to 'text_to_sql_evaluation_results.csv'")

Starting evaluation on 100 test queries...

  0%|          | 0/100 [00:00<?, ?it/s]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  0%|          | 0/100 [00:00<?, ?it/s]

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!

In [19]:
import pandas as pd
from tqdm import tqdm
from unsloth import FastLanguageModel

# 1. Grab 100 test examples from the end of the dataset (unseen data)
test_data = dataset.select(range(len(dataset)-100, len(dataset)))
FastLanguageModel.for_inference(model)

correct_matches = 0
total_tested = len(test_data)
results = []

print(f"Starting evaluation on {total_tested} test queries...\n")

for i in tqdm(range(total_tested)):
    question = test_data[i]["question"]
    context = test_data[i]["context"]
    true_sql = test_data[i]["answer"]
    
    # Format the prompt WITHOUT the answer
    test_prompt = prompt_template.format(
        question=question, 
        context=context, 
        answer=""
    )
    
    # Generate the prediction
    inputs = tokenizer([test_prompt], return_tensors="pt").to("cuda")
    prompt_length = inputs.input_ids.shape[1]
    
    outputs = model.generate(**inputs, max_new_tokens=64, use_cache=True, pad_token_id=tokenizer.eos_token_id)
    
    generated_tokens = outputs[0][prompt_length:]
    generated_sql = tokenizer.decode(generated_tokens, skip_special_tokens=True).strip()
    
    # Normalize strings for fair comparison
    pred_normalized = " ".join(generated_sql.lower().split())
    true_normalized = " ".join(true_sql.lower().split())
    
    is_correct = (pred_normalized == true_normalized)
    if is_correct:
        correct_matches += 1
        
    results.append({
        "Question": question,
        "True SQL": true_sql,
        "Generated SQL": generated_sql,
        "Exact Match": is_correct
    })

accuracy = (correct_matches / total_tested) * 100
print(f"\n✅ Evaluation Complete!")
print(f"📊 Final Exact Match (EM) Accuracy: {accuracy:.2f}%")

# Save the results to a CSV
df_results = pd.DataFrame(results)
df_results.to_csv("text_to_sql_evaluation_results.csv", index=False)
print("💾 Saved detailed results to 'text_to_sql_evaluation_results.csv'")

Starting evaluation on 100 test queries...

  0%|          | 0/100 [00:00<?, ?it/s]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  0%|          | 0/100 [00:00<?, ?it/s]

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!

In [20]:
import pandas as pd
from tqdm import tqdm
from unsloth import FastLanguageModel

# 1. Grab 100 test examples from the end of the dataset (unseen data)
test_data = dataset.select(range(len(dataset)-100, len(dataset)))
FastLanguageModel.for_inference(model)

correct_matches = 0
total_tested = len(test_data)
results = []

print(f"Starting evaluation on {total_tested} test queries...\n")

for i in tqdm(range(total_tested)):
    question = test_data[i]["question"]
    context = test_data[i]["context"]
    true_sql = test_data[i]["answer"]
    
    # Format the prompt WITHOUT the answer
    test_prompt = prompt_template.format(
        question=question, 
        context=context, 
        answer=""
    )
    
    # Explicitly send inputs to cuda:1 to match the multi-GPU setup
    inputs = tokenizer([test_prompt], return_tensors="pt").to("cuda:1")
    prompt_length = inputs.input_ids.shape[1]
    
    outputs = model.generate(**inputs, max_new_tokens=64, use_cache=True, pad_token_id=tokenizer.eos_token_id)
    
    generated_tokens = outputs[0][prompt_length:]
    generated_sql = tokenizer.decode(generated_tokens, skip_special_tokens=True).strip()
    
    # Normalize strings for fair comparison
    pred_normalized = " ".join(generated_sql.lower().split())
    true_normalized = " ".join(true_sql.lower().split())
    
    is_correct = (pred_normalized == true_normalized)
    if is_correct:
        correct_matches += 1
        
    results.append({
        "Question": question,
        "True SQL": true_sql,
        "Generated SQL": generated_sql,
        "Exact Match": is_correct
    })

accuracy = (correct_matches / total_tested) * 100
print(f"\n✅ Evaluation Complete!")
print(f"📊 Final Exact Match (EM) Accuracy: {accuracy:.2f}%")

# Save the results to a CSV
df_results = pd.DataFrame(results)
df_results.to_csv("text_to_sql_evaluation_results.csv", index=False)
print("💾 Saved detailed results to 'text_to_sql_evaluation_results.csv'")

Starting evaluation on 100 test queries...

  0%|          | 0/100 [00:00<?, ?it/s]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  0%|          | 0/100 [00:00<?, ?it/s]

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!

In [21]:
import torch
import pandas as pd
from tqdm import tqdm
from unsloth import FastLanguageModel

# 1. Force the model onto a single device (cuda:0) to clear multi-GPU splits
model.to("cuda:0")
FastLanguageModel.for_inference(model)

# 2. Grab 100 test examples from the end of the dataset (unseen data)
test_data = dataset.select(range(len(dataset)-100, len(dataset)))

correct_matches = 0
total_tested = len(test_data)
results = []

print(f"Starting evaluation on {total_tested} test queries...\n")

for i in tqdm(range(total_tested)):
    question = test_data[i]["question"]
    context = test_data[i]["context"]
    true_sql = test_data[i]["answer"]
    
    # Format the prompt WITHOUT the answer
    test_prompt = prompt_template.format(
        question=question, 
        context=context, 
        answer=""
    )
    
    # Send inputs to cuda:0 to match the single-device model
    inputs = tokenizer([test_prompt], return_tensors="pt").to("cuda:0")
    prompt_length = inputs.input_ids.shape[1]
    
    outputs = model.generate(**inputs, max_new_tokens=64, use_cache=True, pad_token_id=tokenizer.eos_token_id)
    
    generated_tokens = outputs[0][prompt_length:]
    generated_sql = tokenizer.decode(generated_tokens, skip_special_tokens=True).strip()
    
    # Normalize strings for fair comparison
    pred_normalized = " ".join(generated_sql.lower().split())
    true_normalized = " ".join(true_sql.lower().split())
    
    is_correct = (pred_normalized == true_normalized)
    if is_correct:
        correct_matches += 1
        
    results.append({
        "Question": question,
        "True SQL": true_sql,
        "Generated SQL": generated_sql,
        "Exact Match": is_correct
    })

accuracy = (correct_matches / total_tested) * 100
print(f"\n✅ Evaluation Complete!")
print(f"📊 Final Exact Match (EM) Accuracy: {accuracy:.2f}%")

# Save the results to a CSV
df_results = pd.DataFrame(results)
df_results.to_csv("text_to_sql_evaluation_results.csv", index=False)
print("💾 Saved detailed results to 'text_to_sql_evaluation_results.csv'")

Starting evaluation on 100 test queries...

  0%|          | 0/100 [00:00<?, ?it/s]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  0%|          | 0/100 [00:00<?, ?it/s]

RuntimeError: Expected all tensors to be on the same device, but got mat2 is on cuda:0, different from other tensors on cuda:1 (when checking argument in method wrapper_CUDA_mm)

In [22]:
import torch
import pandas as pd
from tqdm import tqdm
from unsloth import FastLanguageModel

# 1. Clear GPU memory and reload the trained model cleanly onto a single device
torch.cuda.empty_cache()

max_seq_length = 2048
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "outputs",  # Loads your newly trained 1000-step checkpoint
    max_seq_length = max_seq_length,
    dtype = None,
    load_in_4bit = True,
)

FastLanguageModel.for_inference(model) # Optimizes model for fast generation

# 2. Grab 100 test examples from the end of the dataset (unseen data)
test_data = dataset.select(range(len(dataset)-100, len(dataset)))

correct_matches = 0
total_tested = len(test_data)
results = []

print(f"Starting evaluation on {total_tested} test queries...\n")

for i in tqdm(range(total_tested)):
    question = test_data[i]["question"]
    context = test_data[i]["context"]
    true_sql = test_data[i]["answer"]
    
    # Format the prompt WITHOUT the answer
    test_prompt = prompt_template.format(
        question=question, 
        context=context, 
        answer=""
    )
    
    # Send inputs to cuda:0
    inputs = tokenizer([test_prompt], return_tensors="pt").to("cuda")
    prompt_length = inputs.input_ids.shape[1]
    
    outputs = model.generate(**inputs, max_new_tokens=64, use_cache=True, pad_token_id=tokenizer.eos_token_id)
    
    generated_tokens = outputs[0][prompt_length:]
    generated_sql = tokenizer.decode(generated_tokens, skip_special_tokens=True).strip()
    
    # Normalize strings for fair comparison
    pred_normalized = " ".join(generated_sql.lower().split())
    true_normalized = " ".join(true_sql.lower().split())
    
    is_correct = (pred_normalized == true_normalized)
    if is_correct:
        correct_matches += 1
        
    results.append({
        "Question": question,
        "True SQL": true_sql,
        "Generated SQL": generated_sql,
        "Exact Match": is_correct
    })

accuracy = (correct_matches / total_tested) * 100
print(f"\n✅ Evaluation Complete!")
print(f"📊 Final Exact Match (EM) Accuracy: {accuracy:.2f}%")

# Save the results to a CSV
df_results = pd.DataFrame(results)
df_results.to_csv("text_to_sql_evaluation_results.csv", index=False)
print("💾 Saved detailed results to 'text_to_sql_evaluation_results.csv'")

RuntimeError: Unsloth: Failed to load model. Both AutoConfig and PeftConfig loading failed.

AutoConfig error: Unrecognized model in outputs. Should have a `model_type` key in its config.json.

PeftConfig error: Can't find 'adapter_config.json' at 'outputs'

In [23]:
import torch
import pandas as pd
from tqdm import tqdm
from unsloth import FastLanguageModel
from peft import PeftModel

print("💾 1. Saving trained adapters locally...")
model.save_pretrained("sql_lora_adapter")
tokenizer.save_pretrained("sql_lora_adapter")

print("🧹 2. Clearing GPU memory...")
torch.cuda.empty_cache()

print("🔄 3. Reloading base model fresh on a single GPU (cuda:0)...")
max_seq_length = 2048
base_model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/llama-3-8b-Instruct-bnb-4bit",
    max_seq_length = max_seq_length,
    dtype = None,
    load_in_4bit = True,
)

print("🔗 4. Attaching your trained adapters...")
model = PeftModel.from_pretrained(base_model, "sql_lora_adapter")
FastLanguageModel.for_inference(model) # Optimizes for fast generation

# 5. Grab 100 test examples from the end of the dataset (unseen data)
test_data = dataset.select(range(len(dataset)-100, len(dataset)))

correct_matches = 0
total_tested = len(test_data)
results = []

print(f"\n🚀 Starting evaluation on {total_tested} test queries...\n")

for i in tqdm(range(total_tested)):
    question = test_data[i]["question"]
    context = test_data[i]["context"]
    true_sql = test_data[i]["answer"]
    
    # Format the prompt WITHOUT the answer
    test_prompt = prompt_template.format(
        question=question, 
        context=context, 
        answer=""
    )
    
    # Send inputs to cuda:0
    inputs = tokenizer([test_prompt], return_tensors="pt").to("cuda:0")
    prompt_length = inputs.input_ids.shape[1]
    
    outputs = model.generate(**inputs, max_new_tokens=64, use_cache=True, pad_token_id=tokenizer.eos_token_id)
    
    generated_tokens = outputs[0][prompt_length:]
    generated_sql = tokenizer.decode(generated_tokens, skip_special_tokens=True).strip()
    
    # Normalize strings for fair comparison
    pred_normalized = " ".join(generated_sql.lower().split())
    true_normalized = " ".join(true_sql.lower().split())
    
    is_correct = (pred_normalized == true_normalized)
    if is_correct:
        correct_matches += 1
        
    results.append({
        "Question": question,
        "True SQL": true_sql,
        "Generated SQL": generated_sql,
        "Exact Match": is_correct
    })

accuracy = (correct_matches / total_tested) * 100
print(f"\n✅ Evaluation Complete!")
print(f"📊 Final Exact Match (EM) Accuracy: {accuracy:.2f}%")

# Save the results to a CSV
df_results = pd.DataFrame(results)
df_results.to_csv("text_to_sql_evaluation_results.csv", index=False)
print("💾 Saved detailed results to 'text_to_sql_evaluation_results.csv'")

💾 1. Saving trained adapters locally...

Unsloth: Restored added_tokens_decoder metadata in sql_lora_adapter/tokenizer_config.json.

🧹 2. Clearing GPU memory...
🔄 3. Reloading base model fresh on a single GPU (cuda:0)...
==((====))==  Unsloth 2026.9.12: Fast Llama patching. Transformers: 5.17.0.
   \\   /|    Tesla T4. Num GPUs = 2. Max memory: 14.562 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

/usr/local/lib/python3.12/dist-packages/huggingface_hub/constants.py:302: FutureWarning: The `HF_HUB_ENABLE_HF_TRANSFER` environment variable is deprecated as 'hf_transfer' is not used anymore. Please use `HF_XET_HIGH_PERFORMANCE` instead to enable high performance transfer with Xet. Visit https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables#hfxethighperformance for more details.
  warnings.warn(

total weights      : 5.208 GiB
no_split classes   : ['LlamaDecoderLayer']
output head        : lm_head -> cuda:1
head headroom      : 0.342 GiB
activation reserve : 4.168 GiB requested
  cuda:0  budget   4.03 GiB  weights  1.486 GiB  free  2.545 GiB  reserve  2.519 GiB
  cuda:1  budget   9.85 GiB  weights  3.721 GiB  free  6.132 GiB  reserve  4.168 GiB   <- output head
note: Bnb4BitHfQuantizer.adjust_max_memory lowered the budget on cuda:0 4.479 -> 4.031 GiB, cuda:1 10.948 -> 9.853 GiB (memory the quantiser keeps for its own load-time buffers)

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

Unsloth: Will load unsloth/llama-3-8b-Instruct-bnb-4bit as a legacy tokenizer.

🔗 4. Attaching your trained adapters...

🚀 Starting evaluation on 100 test queries...

  0%|          | 0/100 [00:00<?, ?it/s]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  1%|          | 1/100 [00:02<04:29,  2.72s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  2%|▏         | 2/100 [00:04<03:42,  2.27s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  3%|▎         | 3/100 [00:06<03:02,  1.88s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  4%|▍         | 4/100 [00:07<02:37,  1.64s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  5%|▌         | 5/100 [00:08<02:34,  1.62s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  6%|▌         | 6/100 [00:11<02:57,  1.89s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  7%|▋         | 7/100 [00:13<02:54,  1.88s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  8%|▊         | 8/100 [00:14<02:46,  1.81s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  9%|▉         | 9/100 [00:16<02:38,  1.74s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 10%|█         | 10/100 [00:18<02:39,  1.78s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 11%|█         | 11/100 [00:19<02:32,  1.71s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 12%|█▏        | 12/100 [00:21<02:31,  1.72s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 13%|█▎        | 13/100 [00:23<02:45,  1.90s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 14%|█▍        | 14/100 [00:26<02:51,  2.00s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 15%|█▌        | 15/100 [00:28<02:47,  1.97s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 16%|█▌        | 16/100 [00:30<02:45,  1.97s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 17%|█▋        | 17/100 [00:32<02:55,  2.12s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 18%|█▊        | 18/100 [00:34<02:56,  2.16s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 19%|█▉        | 19/100 [00:37<03:02,  2.25s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 20%|██        | 20/100 [00:38<02:48,  2.11s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 21%|██        | 21/100 [00:41<02:44,  2.08s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 22%|██▏       | 22/100 [00:42<02:22,  1.83s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 23%|██▎       | 23/100 [00:44<02:24,  1.88s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 24%|██▍       | 24/100 [00:45<02:08,  1.69s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 25%|██▌       | 25/100 [00:48<02:26,  1.95s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 26%|██▌       | 26/100 [00:49<02:14,  1.82s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 27%|██▋       | 27/100 [00:51<02:09,  1.77s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 28%|██▊       | 28/100 [00:52<01:57,  1.63s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 29%|██▉       | 29/100 [00:54<01:58,  1.67s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 30%|███       | 30/100 [00:55<01:57,  1.68s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 31%|███       | 31/100 [00:58<02:07,  1.84s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 32%|███▏      | 32/100 [01:00<02:06,  1.85s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 33%|███▎      | 33/100 [01:01<01:58,  1.76s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 34%|███▍      | 34/100 [01:03<01:52,  1.71s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 35%|███▌      | 35/100 [01:05<01:53,  1.75s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 36%|███▌      | 36/100 [01:06<01:46,  1.67s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 37%|███▋      | 37/100 [01:07<01:39,  1.58s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 38%|███▊      | 38/100 [01:09<01:44,  1.69s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 39%|███▉      | 39/100 [01:11<01:50,  1.81s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 40%|████      | 40/100 [01:14<01:59,  1.99s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 41%|████      | 41/100 [01:15<01:46,  1.80s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 42%|████▏     | 42/100 [01:17<01:45,  1.81s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 43%|████▎     | 43/100 [01:18<01:36,  1.69s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 44%|████▍     | 44/100 [01:20<01:30,  1.61s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 45%|████▌     | 45/100 [01:21<01:24,  1.53s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 46%|████▌     | 46/100 [01:23<01:22,  1.53s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 47%|████▋     | 47/100 [01:25<01:36,  1.82s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 48%|████▊     | 48/100 [01:27<01:26,  1.67s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 49%|████▉     | 49/100 [01:28<01:21,  1.60s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 50%|█████     | 50/100 [01:29<01:13,  1.47s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 51%|█████     | 51/100 [01:31<01:18,  1.61s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 52%|█████▏    | 52/100 [01:33<01:22,  1.71s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 53%|█████▎    | 53/100 [01:35<01:16,  1.63s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 54%|█████▍    | 54/100 [01:36<01:12,  1.57s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 55%|█████▌    | 55/100 [01:37<01:09,  1.54s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 56%|█████▌    | 56/100 [01:39<01:06,  1.51s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 57%|█████▋    | 57/100 [01:40<01:03,  1.47s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 58%|█████▊    | 58/100 [01:42<01:01,  1.45s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 59%|█████▉    | 59/100 [01:43<01:02,  1.53s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 60%|██████    | 60/100 [01:45<01:03,  1.58s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 61%|██████    | 61/100 [01:47<01:05,  1.68s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 62%|██████▏   | 62/100 [01:49<01:02,  1.64s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 63%|██████▎   | 63/100 [01:50<00:57,  1.57s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 64%|██████▍   | 64/100 [01:52<00:56,  1.58s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 65%|██████▌   | 65/100 [01:53<00:53,  1.53s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 66%|██████▌   | 66/100 [01:54<00:50,  1.50s/it]Both `max_new_tokens` (=64) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

✅ Evaluation Complete!
📊 Final Exact Match (EM) Accuracy: 84.00%
💾 Saved detailed results to 'text_to_sql_evaluation_results.csv'